export const ENVIRONMENTS = {
  runway: {
    id: "runway",
    name: "Green Runway Hills",
    skyTop: "#8ee8ff",
    skyBottom: "#eaffd9",
    ground: "#5ecb72",
    groundDark: "#2f9b51",
    accent: "#ffd35a",
    gravity: 980,
    traction: 1,
    wind: 0,
    decorations: ["hangar", "sign", "radar"],
  },
  canyon: {
    id: "canyon",
    name: "Cargo Canyon",
    skyTop: "#ffd3a0",
    skyBottom: "#fff0c7",
    ground: "#c7824f",
    groundDark: "#805236",
    accent: "#46c7d9",
    gravity: 1020,
    traction: 0.96,
    wind: 0,
    decorations: ["crates", "cargo-plane", "bridge"],
  },
  frost: {
    id: "frost",
    name: "Frost Wing Pass",
    skyTop: "#d8f8ff",
    skyBottom: "#f4fbff",
    ground: "#c7ecf8",
    groundDark: "#8dc7d8",
    accent: "#7f59e8",
    gravity: 960,
    traction: 0.7,
    wind: 0.03,
    decorations: ["snow", "ice-marker", "frozen-runway"],
  },
  desert: {
    id: "desert",
    name: "Desert Airfield",
    skyTop: "#ffdca4",
    skyBottom: "#fff5c7",
    ground: "#e8b45d",
    groundDark: "#b97930",
    accent: "#ef5b63",
    gravity: 1000,
    traction: 0.82,
    wind: 0.01,
    decorations: ["dune-sign", "heat", "marker"],
  },
  storm: {
    id: "storm",
    name: "Storm Route",
    skyTop: "#7b8fa8",
    skyBottom: "#d6e7f0",
    ground: "#476879",
    groundDark: "#294252",
    accent: "#ffd35a",
    gravity: 1035,
    traction: 0.78,
    wind: 0.12,
    decorations: ["rain", "turbine", "cloud"],
  },
  moon: {
    id: "moon",
    name: "Moon Terminal",
    skyTop: "#172033",
    skyBottom: "#4b5c8d",
    ground: "#c7cce0",
    groundDark: "#7f849b",
    accent: "#ffd35a",
    gravity: 650,
    traction: 0.72,
    wind: 0,
    decorations: ["planet", "crater", "space-sign"],
  },
  islands: {
    id: "islands",
    name: "Floating Island Trail",
    skyTop: "#9ee9ff",
    skyBottom: "#f4f9ff",
    ground: "#8bd783",
    groundDark: "#4f9d6b",
    accent: "#ff8a3d",
    gravity: 900,
    traction: 0.94,
    wind: 0.05,
    decorations: ["balloon", "island", "cloud-road"],
  },
  volcano: {
    id: "volcano",
    name: "Volcano Flight Path",
    skyTop: "#473046",
    skyBottom: "#fa8a54",
    ground: "#4b3a3a",
    groundDark: "#251d22",
    accent: "#ffd35a",
    gravity: 1040,
    traction: 0.9,
    wind: 0.02,
    decorations: ["lava", "vent", "rock"],
  },
};

export const CAMPAIGN_LEVELS = [
  {
    id: 1,
    name: "Training Hills",
    environment: "runway",
    recommendedVehicle: "baggage-buggy",
    distance: 1900,
    difficulty: 0.72,
    checkpoints: [700, 1350],
    objective: "Travel the full training route and learn steady throttle control.",
    challenge: "Finish without flipping",
    stars: ["Reach the finish", "Collect 60% of coins", "Finish without flipping"],
  },
  {
    id: 2,
    name: "Luggage Lane",
    environment: "runway",
    recommendedVehicle: "baggage-buggy",
    distance: 2300,
    difficulty: 0.84,
    checkpoints: [760, 1500],
    objective: "Collect fuel cells across a longer luggage route and clear repeated bumps.",
    challenge: "Collect a Lost Luggage Token",
    stars: ["Reach the finish", "Collect 60% of coins", "Collect the luggage token"],
  },
  {
    id: 3,
    name: "Cloud Valley",
    environment: "islands",
    recommendedVehicle: "cloud-rover",
    distance: 2750,
    difficulty: 0.98,
    checkpoints: [820, 1640, 2300],
    objective: "Carry momentum through a long chain of deep valleys.",
    challenge: "Complete a long jump",
    stars: ["Reach the finish", "Collect 65% of coins", "Complete a long jump"],
  },
  {
    id: 4,
    name: "Runway Ridges",
    environment: "runway",
    recommendedVehicle: "runway-jeep",
    distance: 3200,
    difficulty: 1.08,
    checkpoints: [900, 1800, 2650],
    objective: "Climb extended runway ridges and manage fuel between longer downhill jumps.",
    challenge: "Finish with 25% fuel",
    stars: ["Reach the finish", "Collect 70% of coins", "Finish with 25% fuel"],
  },
  {
    id: 5,
    name: "Cargo Canyon",
    environment: "canyon",
    recommendedVehicle: "cargo-truck",
    distance: 3700,
    difficulty: 1.2,
    checkpoints: [950, 1950, 3000],
    objective: "Cross a long cargo canyon while dodging repeated rocks, bridges, and crates.",
    challenge: "Use no checkpoint restart",
    stars: ["Reach the finish", "Collect 70% of coins", "No checkpoint restart"],
  },
  {
    id: 6,
    name: "Frost Wing Pass",
    environment: "frost",
    recommendedVehicle: "cloud-rover",
    distance: 4200,
    difficulty: 1.32,
    checkpoints: [1050, 2200, 3350],
    objective: "Handle a long icy pass with low traction, ramps, and careful landings.",
    challenge: "Perfect landing",
    stars: ["Reach the finish", "Collect 70% of coins", "Complete a perfect landing"],
  },
  {
    id: 7,
    name: "Desert Airfield",
    environment: "desert",
    recommendedVehicle: "rescue-tractor",
    distance: 4700,
    difficulty: 1.42,
    checkpoints: [1150, 2450, 3750],
    objective: "Travel across soft dunes and long climbs without wasting fuel.",
    challenge: "Collect the hidden Golden Propeller",
    stars: ["Reach the finish", "Collect 75% of coins", "Find the Golden Propeller"],
  },
  {
    id: 8,
    name: "Storm Route",
    environment: "storm",
    recommendedVehicle: "runway-jeep",
    distance: 5250,
    difficulty: 1.55,
    checkpoints: [1250, 2700, 4200],
    objective: "Push through a long storm route with wet slopes, side wind, and tighter fuel.",
    challenge: "Near-crash recovery",
    stars: ["Reach the finish", "Collect 75% of coins", "Recover from a near crash"],
  },
  {
    id: 9,
    name: "Moon Terminal",
    environment: "moon",
    recommendedVehicle: "moon-hopper",
    distance: 5750,
    difficulty: 1.45,
    checkpoints: [1300, 2950, 4600],
    objective: "Use low gravity across a long lunar route of controlled jumps.",
    challenge: "Complete one backflip",
    stars: ["Reach the finish", "Collect 75% of coins", "Complete a backflip"],
  },
  {
    id: 10,
    name: "Floating Island Trail",
    environment: "islands",
    recommendedVehicle: "propeller-buggy",
    distance: 6300,
    difficulty: 1.68,
    checkpoints: [1400, 3100, 4850],
    objective: "Clear long-distance gaps between cloud roads and floating islands.",
    challenge: "Use a special ability in the air",
    stars: ["Reach the finish", "Collect 80% of coins", "Use an air ability"],
  },
  {
    id: 11,
    name: "Volcano Flight Path",
    environment: "volcano",
    recommendedVehicle: "cargo-truck",
    distance: 6900,
    difficulty: 1.82,
    checkpoints: [1500, 3400, 5350],
    objective: "Survive a long volcano flight path with rocks, vents, and steep heat ramps.",
    challenge: "Complete a double flip",
    stars: ["Reach the finish", "Collect 80% of coins", "Complete a double flip"],
  },
  {
    id: 12,
    name: "Captain's Final Climb",
    environment: "storm",
    recommendedVehicle: "propeller-buggy",
    distance: 7600,
    difficulty: 1.95,
    checkpoints: [1600, 3700, 5900],
    objective: "Conquer the longest final climb with sustained fuel management and precise landings.",
    challenge: "Finish with a combo multiplier",
    stars: ["Reach the finish", "Collect 80% of coins", "Finish with a combo"],
  },
];

export function getLevel(levelId) {
  return CAMPAIGN_LEVELS.find((level) => level.id === Number(levelId)) || CAMPAIGN_LEVELS[0];
}

export function getEnvironment(environmentId) {
  return ENVIRONMENTS[environmentId] || ENVIRONMENTS.runway;
}

export function environmentList() {
  return Object.values(ENVIRONMENTS);
}

export function levelStars(level, result) {
  if (!result?.completed) return 0;
  let stars = 1;
  const coinRatio = result.totalCoins ? result.coinsCollected / result.totalCoins : 0;
  if (coinRatio >= (level.id >= 7 ? 0.75 : 0.6)) stars = 2;
  if (result.challengeComplete || (coinRatio >= 0.8 && result.fuelLeft >= 25)) stars = 3;
  return stars;
}
