export const ENVIRONMENTS = {
  runway: {
    id: "runway",
    name: "Green Runway Hills",
    skyTop: "#8ee8ff",
    skyBottom: "#eaffd9",
    ground: "#5ecb72",
    groundDark: "#2f9b51",
    accent: "#ffd35a",
    gravity: 980,
    traction: 1,
    wind: 0,
    decorations: ["hangar", "sign", "radar"],
  },
  canyon: {
    id: "canyon",
    name: "Cargo Canyon",
    skyTop: "#ffd3a0",
    skyBottom: "#fff0c7",
    ground: "#c7824f",
    groundDark: "#805236",
    accent: "#46c7d9",
    gravity: 1020,
    traction: 0.96,
    wind: 0,
    decorations: ["crates", "cargo-plane", "bridge"],
  },
  frost: {
    id: "frost",
    name: "Frost Wing Pass",
    skyTop: "#d8f8ff",
    skyBottom: "#f4fbff",
    ground: "#c7ecf8",
    groundDark: "#8dc7d8",
    accent: "#7f59e8",
    gravity: 960,
    traction: 0.7,
    wind: 0.03,
    decorations: ["snow", "ice-marker", "frozen-runway"],
  },
  desert: {
    id: "desert",
    name: "Desert Airfield",
    skyTop: "#ffdca4",
    skyBottom: "#fff5c7",
    ground: "#e8b45d",
    groundDark: "#b97930",
    accent: "#ef5b63",
    gravity: 1000,
    traction: 0.82,
    wind: 0.01,
    decorations: ["dune-sign", "heat", "marker"],
  },
  storm: {
    id: "storm",
    name: "Storm Route",
    skyTop: "#7b8fa8",
    skyBottom: "#d6e7f0",
    ground: "#476879",
    groundDark: "#294252",
    accent: "#ffd35a",
    gravity: 1035,
    traction: 0.78,
    wind: 0.12,
    decorations: ["rain", "turbine", "cloud"],
  },
  moon: {
    id: "moon",
    name: "Moon Terminal",
    skyTop: "#172033",
    skyBottom: "#4b5c8d",
    ground: "#c7cce0",
    groundDark: "#7f849b",
    accent: "#ffd35a",
    gravity: 650,
    traction: 0.72,
    wind: 0,
    decorations: ["planet", "crater", "space-sign"],
  },
  islands: {
    id: "islands",
    name: "Floating Island Trail",
    skyTop: "#9ee9ff",
    skyBottom: "#f4f9ff",
    ground: "#8bd783",
    groundDark: "#4f9d6b",
    accent: "#ff8a3d",
    gravity: 900,
    traction: 0.94,
    wind: 0.05,
    decorations: ["balloon", "island", "cloud-road"],
  },
  volcano: {
    id: "volcano",
    name: "Volcano Flight Path",
    skyTop: "#473046",
    skyBottom: "#fa8a54",
    ground: "#4b3a3a",
    groundDark: "#251d22",
    accent: "#ffd35a",
    gravity: 1040,
    traction: 0.9,
    wind: 0.02,
    decorations: ["lava", "vent", "rock"],
  },
};

export const METRES_PER_WORLD_UNIT = 0.08;

export function worldUnitsToMetres(worldUnits) {
  return Math.max(0, Math.floor((worldUnits || 0) * METRES_PER_WORLD_UNIT));
}

const ENVIRONMENT_AVERAGE_SPEED = {
  runway: 320,
  canyon: 292,
  frost: 258,
  desert: 284,
  storm: 266,
  moon: 252,
  islands: 276,
  volcano: 262,
};

const TERRAIN_MULTIPLIER = {
  easy: 1.05,
  medium: 1.12,
  hard: 1.2,
  expert: 1.3,
};

function levelDistance({ environment, targetDurationSeconds, terrainDifficulty, majorSections }) {
  const speed = ENVIRONMENT_AVERAGE_SPEED[environment] || 290;
  const multiplier = TERRAIN_MULTIPLIER[terrainDifficulty] || 1.12;
  const worldUnits = speed * targetDurationSeconds * multiplier + majorSections * 140;
  return Math.ceil(worldUnits / 1000) * 1000;
}

function checkpointsFor(distance, count) {
  return Array.from({ length: count }, (_, index) => Math.round(distance * ((index + 1) / (count + 1)) / 100) * 100);
}

function campaignLevel(config) {
  const distance = levelDistance(config);
  return {
    ...config,
    expectedAverageSpeed: ENVIRONMENT_AVERAGE_SPEED[config.environment] || 290,
    distance,
    checkpoints: checkpointsFor(distance, config.checkpointCount),
  };
}

export const CAMPAIGN_LEVELS = [
  campaignLevel({
    id: 1,
    name: "Training Hills",
    environment: "runway",
    recommendedVehicle: "baggage-buggy",
    difficulty: 0.72,
    targetDurationSeconds: 210,
    minimumDurationSeconds: 180,
    checkpointCount: 3,
    obstacleDensity: "low",
    minimumObstacleGapSeconds: 13,
    recoverySectionFrequency: 3,
    terrainDifficulty: "easy",
    fuelIntervalSeconds: 34,
    majorSections: 14,
    objective: "Travel a full training route of rolling hills, checkpoints, and recovery roads.",
    challenge: "Finish without flipping",
    stars: ["Reach the finish", "Collect 60% of coins", "Finish without flipping"],
  }),
  campaignLevel({
    id: 2,
    name: "Luggage Lane",
    environment: "runway",
    recommendedVehicle: "baggage-buggy",
    difficulty: 0.84,
    targetDurationSeconds: 240,
    minimumDurationSeconds: 210,
    checkpointCount: 4,
    obstacleDensity: "low-medium",
    minimumObstacleGapSeconds: 11,
    recoverySectionFrequency: 3,
    terrainDifficulty: "easy",
    fuelIntervalSeconds: 32,
    majorSections: 16,
    objective: "Collect fuel cells across a long luggage route with clear recovery space.",
    challenge: "Collect a Lost Luggage Token",
    stars: ["Reach the finish", "Collect 60% of coins", "Collect the luggage token"],
  }),
  campaignLevel({
    id: 3,
    name: "Cloud Valley",
    environment: "islands",
    recommendedVehicle: "cloud-rover",
    difficulty: 0.98,
    targetDurationSeconds: 260,
    minimumDurationSeconds: 230,
    checkpointCount: 4,
    obstacleDensity: "medium",
    minimumObstacleGapSeconds: 10,
    recoverySectionFrequency: 3,
    terrainDifficulty: "medium",
    fuelIntervalSeconds: 30,
    majorSections: 18,
    objective: "Carry momentum through a long chain of valleys, ramps, and safe landings.",
    challenge: "Complete a long jump",
    stars: ["Reach the finish", "Collect 65% of coins", "Complete a long jump"],
  }),
  campaignLevel({
    id: 4,
    name: "Runway Ridges",
    environment: "runway",
    recommendedVehicle: "runway-jeep",
    difficulty: 1.08,
    targetDurationSeconds: 275,
    minimumDurationSeconds: 240,
    checkpointCount: 4,
    obstacleDensity: "medium",
    minimumObstacleGapSeconds: 9,
    recoverySectionFrequency: 3,
    terrainDifficulty: "medium",
    fuelIntervalSeconds: 29,
    majorSections: 20,
    objective: "Climb extended runway ridges and manage fuel between downhill jumps.",
    challenge: "Finish with 25% fuel",
    stars: ["Reach the finish", "Collect 70% of coins", "Finish with 25% fuel"],
  }),
  campaignLevel({
    id: 5,
    name: "Cargo Canyon",
    environment: "canyon",
    recommendedVehicle: "cargo-truck",
    difficulty: 1.2,
    targetDurationSeconds: 290,
    minimumDurationSeconds: 250,
    checkpointCount: 5,
    obstacleDensity: "medium",
    minimumObstacleGapSeconds: 9,
    recoverySectionFrequency: 3,
    terrainDifficulty: "medium",
    fuelIntervalSeconds: 28,
    majorSections: 21,
    objective: "Cross a long cargo canyon with spaced bridges, rocks, and crate challenges.",
    challenge: "Use no checkpoint restart",
    stars: ["Reach the finish", "Collect 70% of coins", "No checkpoint restart"],
  }),
  campaignLevel({
    id: 6,
    name: "Frost Wing Pass",
    environment: "frost",
    recommendedVehicle: "cloud-rover",
    difficulty: 1.32,
    targetDurationSeconds: 300,
    minimumDurationSeconds: 260,
    checkpointCount: 5,
    obstacleDensity: "medium",
    minimumObstacleGapSeconds: 10,
    recoverySectionFrequency: 3,
    terrainDifficulty: "medium",
    fuelIntervalSeconds: 28,
    majorSections: 22,
    objective: "Handle a long icy pass with braking areas before slippery downhill sections.",
    challenge: "Perfect landing",
    stars: ["Reach the finish", "Collect 70% of coins", "Complete a perfect landing"],
  }),
  campaignLevel({
    id: 7,
    name: "Desert Airfield",
    environment: "desert",
    recommendedVehicle: "rescue-tractor",
    difficulty: 1.42,
    targetDurationSeconds: 330,
    minimumDurationSeconds: 290,
    checkpointCount: 5,
    obstacleDensity: "medium-high",
    minimumObstacleGapSeconds: 8,
    recoverySectionFrequency: 4,
    terrainDifficulty: "hard",
    fuelIntervalSeconds: 27,
    majorSections: 25,
    objective: "Travel across long dunes, visible fuel lines, and open recovery sections.",
    challenge: "Collect the hidden Golden Propeller",
    stars: ["Reach the finish", "Collect 75% of coins", "Find the Golden Propeller"],
  }),
  campaignLevel({
    id: 8,
    name: "Storm Route",
    environment: "storm",
    recommendedVehicle: "runway-jeep",
    difficulty: 1.55,
    targetDurationSeconds: 345,
    minimumDurationSeconds: 300,
    checkpointCount: 5,
    obstacleDensity: "medium-high",
    minimumObstacleGapSeconds: 9,
    recoverySectionFrequency: 4,
    terrainDifficulty: "hard",
    fuelIntervalSeconds: 27,
    majorSections: 27,
    objective: "Push through a long storm route with wider reaction distances and side wind.",
    challenge: "Near-crash recovery",
    stars: ["Reach the finish", "Collect 75% of coins", "Recover from a near crash"],
  }),
  campaignLevel({
    id: 9,
    name: "Moon Terminal",
    environment: "moon",
    recommendedVehicle: "moon-hopper",
    difficulty: 1.45,
    targetDurationSeconds: 350,
    minimumDurationSeconds: 305,
    checkpointCount: 6,
    obstacleDensity: "medium-high",
    minimumObstacleGapSeconds: 10,
    recoverySectionFrequency: 4,
    terrainDifficulty: "hard",
    fuelIntervalSeconds: 28,
    majorSections: 28,
    objective: "Use low gravity across long jump sections with large landing zones.",
    challenge: "Complete one backflip",
    stars: ["Reach the finish", "Collect 75% of coins", "Complete a backflip"],
  }),
  campaignLevel({
    id: 10,
    name: "Floating Island Trail",
    environment: "islands",
    recommendedVehicle: "propeller-buggy",
    difficulty: 1.68,
    targetDurationSeconds: 365,
    minimumDurationSeconds: 320,
    checkpointCount: 6,
    obstacleDensity: "high",
    minimumObstacleGapSeconds: 7,
    recoverySectionFrequency: 4,
    terrainDifficulty: "hard",
    fuelIntervalSeconds: 26,
    majorSections: 30,
    objective: "Clear long connected islands, safe landing zones, and visible cloud gaps.",
    challenge: "Use a special ability in the air",
    stars: ["Reach the finish", "Collect 80% of coins", "Use an air ability"],
  }),
  campaignLevel({
    id: 11,
    name: "Volcano Flight Path",
    environment: "volcano",
    recommendedVehicle: "cargo-truck",
    difficulty: 1.82,
    targetDurationSeconds: 380,
    minimumDurationSeconds: 335,
    checkpointCount: 6,
    obstacleDensity: "high",
    minimumObstacleGapSeconds: 7,
    recoverySectionFrequency: 4,
    terrainDifficulty: "expert",
    fuelIntervalSeconds: 26,
    majorSections: 32,
    objective: "Survive a long volcano flight path with warning roads before vents.",
    challenge: "Complete a double flip",
    stars: ["Reach the finish", "Collect 80% of coins", "Complete a double flip"],
  }),
  campaignLevel({
    id: 12,
    name: "Captain's Final Climb",
    environment: "storm",
    recommendedVehicle: "propeller-buggy",
    difficulty: 1.95,
    targetDurationSeconds: 450,
    minimumDurationSeconds: 390,
    checkpointCount: 7,
    obstacleDensity: "varied",
    minimumObstacleGapSeconds: 6,
    recoverySectionFrequency: 4,
    terrainDifficulty: "expert",
    fuelIntervalSeconds: 25,
    majorSections: 35,
    objective: "Conquer the longest final climb with sustained fuel management and precise landings.",
    challenge: "Finish with a combo multiplier",
    stars: ["Reach the finish", "Collect 80% of coins", "Finish with a combo"],
  }),
];

export function getLevel(levelId) {
  return CAMPAIGN_LEVELS.find((level) => level.id === Number(levelId)) || CAMPAIGN_LEVELS[0];
}

export function getEnvironment(environmentId) {
  return ENVIRONMENTS[environmentId] || ENVIRONMENTS.runway;
}

export function environmentList() {
  return Object.values(ENVIRONMENTS);
}

export function levelStars(level, result) {
  if (!result?.completed) return 0;
  let stars = 1;
  const coinRatio = result.totalCoins ? result.coinsCollected / result.totalCoins : 0;
  if (coinRatio >= (level.id >= 7 ? 0.75 : 0.6)) stars = 2;
  if (result.challengeComplete || (coinRatio >= 0.8 && result.fuelLeft >= 25)) stars = 3;
  return stars;
}
