export const ENVIRONMENTS = {
  runway: {
    id: "runway",
    name: "Green Runway Hills",
    skyTop: "#8ee8ff",
    skyBottom: "#eaffd9",
    ground: "#5ecb72",
    groundDark: "#2f9b51",
    accent: "#ffd35a",
    gravity: 980,
    traction: 1,
    wind: 0,
    decorations: ["hangar", "sign", "radar"],
  },
  canyon: {
    id: "canyon",
    name: "Cargo Canyon",
    skyTop: "#ffd3a0",
    skyBottom: "#fff0c7",
    ground: "#c7824f",
    groundDark: "#805236",
    accent: "#46c7d9",
    gravity: 1020,
    traction: 0.96,
    wind: 0,
    decorations: ["crates", "cargo-plane", "bridge"],
  },
  frost: {
    id: "frost",
    name: "Frost Wing Pass",
    skyTop: "#d8f8ff",
    skyBottom: "#f4fbff",
    ground: "#c7ecf8",
    groundDark: "#8dc7d8",
    accent: "#7f59e8",
    gravity: 960,
    traction: 0.7,
    wind: 0.03,
    decorations: ["snow", "ice-marker", "frozen-runway"],
  },
  desert: {
    id: "desert",
    name: "Desert Airfield",
    skyTop: "#ffdca4",
    skyBottom: "#fff5c7",
    ground: "#e8b45d",
    groundDark: "#b97930",
    accent: "#ef5b63",
    gravity: 1000,
    traction: 0.82,
    wind: 0.01,
    decorations: ["dune-sign", "heat", "marker"],
  },
  storm: {
    id: "storm",
    name: "Storm Route",
    skyTop: "#7b8fa8",
    skyBottom: "#d6e7f0",
    ground: "#476879",
    groundDark: "#294252",
    accent: "#ffd35a",
    gravity: 1035,
    traction: 0.78,
    wind: 0.12,
    decorations: ["rain", "turbine", "cloud"],
  },
  moon: {
    id: "moon",
    name: "Moon Terminal",
    skyTop: "#172033",
    skyBottom: "#4b5c8d",
    ground: "#c7cce0",
    groundDark: "#7f849b",
    accent: "#ffd35a",
    gravity: 650,
    traction: 0.72,
    wind: 0,
    decorations: ["planet", "crater", "space-sign"],
  },
  islands: {
    id: "islands",
    name: "Floating Island Trail",
    skyTop: "#9ee9ff",
    skyBottom: "#f4f9ff",
    ground: "#8bd783",
    groundDark: "#4f9d6b",
    accent: "#ff8a3d",
    gravity: 900,
    traction: 0.94,
    wind: 0.05,
    decorations: ["balloon", "island", "cloud-road"],
  },
  volcano: {
    id: "volcano",
    name: "Volcano Flight Path",
    skyTop: "#473046",
    skyBottom: "#fa8a54",
    ground: "#4b3a3a",
    groundDark: "#251d22",
    accent: "#ffd35a",
    gravity: 1040,
    traction: 0.9,
    wind: 0.02,
    decorations: ["lava", "vent", "rock"],
  },
};

export const CAMPAIGN_LEVELS = [
  {
    id: 1,
    name: "Training Hills",
    environment: "runway",
    recommendedVehicle: "baggage-buggy",
    distance: 1050,
    difficulty: 0.55,
    checkpoints: [520],
    objective: "Reach the finish and learn throttle control.",
    challenge: "Finish without flipping",
    stars: ["Reach the finish", "Collect 60% of coins", "Finish without flipping"],
  },
  {
    id: 2,
    name: "Luggage Lane",
    environment: "runway",
    recommendedVehicle: "baggage-buggy",
    distance: 1240,
    difficulty: 0.68,
    checkpoints: [600],
    objective: "Collect fuel cells and clear luggage bumps.",
    challenge: "Collect a Lost Luggage Token",
    stars: ["Reach the finish", "Collect 60% of coins", "Collect the luggage token"],
  },
  {
    id: 3,
    name: "Cloud Valley",
    environment: "islands",
    recommendedVehicle: "cloud-rover",
    distance: 1420,
    difficulty: 0.82,
    checkpoints: [640, 1040],
    objective: "Use momentum through the deep valleys.",
    challenge: "Complete a long jump",
    stars: ["Reach the finish", "Collect 65% of coins", "Complete a long jump"],
  },
  {
    id: 4,
    name: "Runway Ridges",
    environment: "runway",
    recommendedVehicle: "runway-jeep",
    distance: 1560,
    difficulty: 0.94,
    checkpoints: [760, 1200],
    objective: "Climb long ridges and land short downhill jumps.",
    challenge: "Finish with 25% fuel",
    stars: ["Reach the finish", "Collect 70% of coins", "Finish with 25% fuel"],
  },
  {
    id: 5,
    name: "Cargo Canyon",
    environment: "canyon",
    recommendedVehicle: "cargo-truck",
    distance: 1740,
    difficulty: 1.05,
    checkpoints: [780, 1320],
    objective: "Cross bridges and dodge rolling cargo.",
    challenge: "Use no checkpoint restart",
    stars: ["Reach the finish", "Collect 70% of coins", "No checkpoint restart"],
  },
  {
    id: 6,
    name: "Frost Wing Pass",
    environment: "frost",
    recommendedVehicle: "cloud-rover",
    distance: 1880,
    difficulty: 1.12,
    checkpoints: [900, 1450],
    objective: "Handle ice ramps and low traction.",
    challenge: "Perfect landing",
    stars: ["Reach the finish", "Collect 70% of coins", "Complete a perfect landing"],
  },
  {
    id: 7,
    name: "Desert Airfield",
    environment: "desert",
    recommendedVehicle: "rescue-tractor",
    distance: 2020,
    difficulty: 1.18,
    checkpoints: [980, 1540],
    objective: "Climb soft dunes without wasting fuel.",
    challenge: "Collect the hidden Golden Propeller",
    stars: ["Reach the finish", "Collect 75% of coins", "Find the Golden Propeller"],
  },
  {
    id: 8,
    name: "Storm Route",
    environment: "storm",
    recommendedVehicle: "runway-jeep",
    distance: 2180,
    difficulty: 1.28,
    checkpoints: [1040, 1660],
    objective: "Push through wet slopes and side wind.",
    challenge: "Near-crash recovery",
    stars: ["Reach the finish", "Collect 75% of coins", "Recover from a near crash"],
  },
  {
    id: 9,
    name: "Moon Terminal",
    environment: "moon",
    recommendedVehicle: "moon-hopper",
    distance: 2300,
    difficulty: 1.18,
    checkpoints: [1100, 1760],
    objective: "Use low gravity for long controlled jumps.",
    challenge: "Complete one backflip",
    stars: ["Reach the finish", "Collect 75% of coins", "Complete a backflip"],
  },
  {
    id: 10,
    name: "Floating Island Trail",
    environment: "islands",
    recommendedVehicle: "propeller-buggy",
    distance: 2480,
    difficulty: 1.36,
    checkpoints: [900, 1540, 2100],
    objective: "Clear gaps between cloud roads.",
    challenge: "Use a special ability in the air",
    stars: ["Reach the finish", "Collect 80% of coins", "Use an air ability"],
  },
  {
    id: 11,
    name: "Volcano Flight Path",
    environment: "volcano",
    recommendedVehicle: "cargo-truck",
    distance: 2650,
    difficulty: 1.46,
    checkpoints: [1040, 1780, 2320],
    objective: "Dodge rocks and ride steep heat ramps.",
    challenge: "Complete a double flip",
    stars: ["Reach the finish", "Collect 80% of coins", "Complete a double flip"],
  },
  {
    id: 12,
    name: "Captain's Final Climb",
    environment: "storm",
    recommendedVehicle: "propeller-buggy",
    distance: 2920,
    difficulty: 1.6,
    checkpoints: [1020, 1760, 2440],
    objective: "Conquer the long final hill.",
    challenge: "Finish with a combo multiplier",
    stars: ["Reach the finish", "Collect 80% of coins", "Finish with a combo"],
  },
];

export function getLevel(levelId) {
  return CAMPAIGN_LEVELS.find((level) => level.id === Number(levelId)) || CAMPAIGN_LEVELS[0];
}

export function getEnvironment(environmentId) {
  return ENVIRONMENTS[environmentId] || ENVIRONMENTS.runway;
}

export function environmentList() {
  return Object.values(ENVIRONMENTS);
}

export function levelStars(level, result) {
  if (!result?.completed) return 0;
  let stars = 1;
  const coinRatio = result.totalCoins ? result.coinsCollected / result.totalCoins : 0;
  if (coinRatio >= (level.id >= 7 ? 0.75 : 0.6)) stars = 2;
  if (result.challengeComplete || (coinRatio >= 0.8 && result.fuelLeft >= 25)) stars = 3;
  return stars;
}
